version: '3.4'

services:
  clang:
    image: clang-cpp
    container_name: clang-cpp
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/usr/src
